modLoader = "kotlinforforge"
loaderVersion = "[5,)"
license = "LicenseRef-ZLA"

[[mods]]
modId = "armsrace"
version = "${version}"
displayName = "ArmsRace"
authors = "aleksti21"
description = '''
A mod that allows you to recreate the arms race mode from CS2 in Minecraft
'''

[[dependencies.armsrace]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armsrace]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.armsrace]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.armsrace]]
modId = "kotlinforforge"
type = "required"
versionRange = "[5,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.armsrace]]
modId="nbttodata"
type="required"
versionRange="[0.1.1-alpha,)"
ordering="NONE"
side="BOTH"